kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logmetrics
subjects:
  - kind: ServiceAccount
    name: logmetrics
roleRef:
  kind: ClusterRole
  name: logmetrics
  apiGroup: rbac.authorization.k8s.io
