apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logmetrics
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
