apiVersion: v1
kind: Service
metadata:
  name: logmetrics
  labels:
    name: logmetrics
spec:
  type: ClusterIP
  selector:
    name: logmetrics
  ports:
    - name: metrics
      port: 9748
      protocol: TCP
      targetPort: metrics
