{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "logmetrics.rbacName" . }}
  labels:
    {{- include "logmetrics.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "logmetrics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "logmetrics.rbacName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
