apiVersion: v1
kind: Service
metadata:
  name: {{ include "logmetrics.fullname" . }}
  labels:
    {{- include "logmetrics.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9748
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "logmetrics.selectorLabels" . | nindent 4 }}
